### ISSUE TITLE
버트 모델 컨버전 관련

### ISSUE THREAD

**Issue by kimsijin33** [monologg/KoBERT-Transformers#5]
구글 mutilingual BERT 로 만들어진 프로그램을
 koBert 로 전환 가능할까요?

**Comment by monologg** [comment]
Embedding 부분을 제외한 Attention 부분은 가져올 수 있겠지만, 
애초에 두 모델의 vocab이 전혀 다르기 때문에 사실상 전환이 많이 어려울 것 같습니다
