### ISSUE TITLE
504 Gateway Timeout 문제 질문드립니다.

### ISSUE THREAD

**Issue by jaehong-k** [monologg/KoBERT-Transformers#9]
안녕하세요! 늘 좋은 모델을 공유해주시니 정말 감사합니다.
그동안 KoBERT를 허깅페이스("monologg/kobert")를 통해 로드를 하곤 했습니다. 그런데, 오늘 갑작스럽게 kobert가 로드 되지 않고 504 Gateway Timeout 라는 에러메시지를 출력해 글을 남깁니다.허깅페이스 홈페이지에 웹페이지로 접속해도 동일한 오류가 나 글을 남기게 됐습니다.
해당 문제를 어떻게 해결할 수 있을까요?!
![image](https://user-images.githubusercontent.com/68909968/204211924-18c45a9d-8c36-4565-b444-e85084864b91.png)

감사합니다.

**Comment by monologg** [comment]
현재 허깅페이스 서버가 다운된걸로 알고 있습니다. 참고바랍니다.

![Screenshot_20221128-154912](https://user-images.githubusercontent.com/28896432/204212282-44d3b43e-ce8a-41aa-8815-e34052ef5fc4.png)
